---

- name: source-hg | Ensure mercurial installed
  apt: pkg=mercurial
  sudo: yes

- name: source-hg | Ensure the repositories is synced
  hg:
    dest: "{{item.dest|default(source_default_dest)}}"
    force: "{{item.force|default('yes')}}"
    purge: "{{item.purge|default('no')}}"
    repo: "{{item.repo}}"
    revision: "{{item.revision|default('default')}}"
  when: item.dest|default("") != ""
  with_items: source_sources
