---

- name: source-hosts | Check if known_hosts exists
  stat: path={{source_known_hosts_file}}
  register: known_hosts_file

- name: source-hosts | Update known hosts
  shell: ssh-keyscan -H {{item}} >> {{ source_known_hosts_file }}
  when: not known_hosts_file.stat.exists
  with_items: source_known_hosts
