---

- include: configure.yml
  tags: [source, source-configure]

- include: git.yml
  when: source_sources_type == 'git'
  tags: [source, source-git]

- include: hg.yml
  when: source_sources_type == 'hg'
  tags: [source, source-hg]
