---

- include: configure.yml
  tags: [source, source-configure]

- include: git.yml repo=item
  when: source_sources_type == 'git'
  tags: [source, source-git]

- include: hg.yml
  when: source_sources_type == 'hg'
  tags: [source, source-hg]

- name: Fix rights
  file: name={{item.dest|default('source_default_dest')}} owner={{source_user}} recurse=yes
  with_items: source_sources
  tags: [source]
